apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deploy
  labels:
    app: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: webapp
          image: mrudulaa666/webapp
          ports:
            - containerPort: 80
