apiVersion: v1
kind: Service
metadata:
  name: demo1
  labels:
    app: demo-app
spec:
  selector:
    app: tom-cat
  type: NodePort
  ports:
    - nodePort: 31000
      port: 80
      targetPort: 80
